name: Krom

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Submodules
      run: |
        git clone --recursive https://github.com/armory3d/Kha.git --depth 1 examples/Nodes/Kha
        git clone https://github.com/armory3d/nodejs_bin.git --depth 1 examples/Nodes/nodejs_bin
    - name: Compile
      run: |
        cd examples/Nodes
        nodejs_bin/node-linux64 Kha/make.js krom --shaderversion 330
